name: Workflow 1

on:
  push:
    branches:
      - main  # Ce workflow se déclenche sur un push sur la branche `main`

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Task 1
        run: |
          echo "Exécution de la tâche 1"
