name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]  # Nom du workflow précédent à suivre
    types:
      - completed  # Le workflow 2 s'exécutera après la fin de workflow 1 (qu'il soit réussi ou échoué)

jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Task 2
        run: |
          echo "Exécution de la tâche 2"
